In [2]:
# tp avec le text en francais et en anglais 

import re 

with open("/Users/mohamedtbh/Desktop/M1_IA/TF_IDF/Eval_Formation_Etranger_fr.txt", "r") as file:
    content = file.read()
print(content)

content_splited = re.split(r"[.]" , content)

liste_of_sentences = list(content_splited)

print(f" the content splited :  {content_splited}")


list_of_tokens = []

for sentence in liste_of_sentences:
    tokens = sentence.split()
    list_of_tokens.append(tokens) 
    
print(list_of_tokens)

FileNotFoundError: [Errno 2] No such file or directory: '/Users/mohamedtbh/Desktop/M1_IA/TF_IDF/Eval_Formation_Etranger_fr.txt'

In [20]:
import re

def remove_punctuation(text):
    """Remove punctuation from the text."""
    return re.sub(r'[^\w\s]', '', text)

def convert_to_lowercase(text):
    """Convert the text to lowercase."""
    return text.lower()

def split_into_sentences(text):
    """Split the text into sentences using punctuation."""
    sentences = re.split(r'[.!?;:]', text)
    return [sentence.strip() for sentence in sentences if sentence.strip()]

def tokenize(text):
    """Tokenize the text into words."""
    return text.split()

def remove_duplicates(tokens):
    """Remove duplicates from the list of tokens while preserving order."""
    return list(dict.fromkeys(tokens))

def count_sentences(sentences):
    """Count the number of sentences."""
    return len(sentences)

def count_tokens(tokens):
    """Count the total number of tokens."""
    return len(tokens)

def count_unique_tokens(unique_tokens):
    """Count the number of unique tokens."""
    return len(unique_tokens)

# Exemple de texte - remplacez ceci par votre texte
full_text = """
La confiance que vous venez de me témoigner, je veux y répondre en m'engageant dans l'action avec détermination.
Mes chers compatriotes de métropole, d'outre-mer et de l'étranger,
Nous venons de vivre un temps de grave inquiétude pour la Nation.
Mais ce soir, dans un grand élan la France a réaffirmé son attachement aux valeurs de la République.
Je salue la France, fidèle à elle-même, fidèle à ses grands idéaux, fidèle à sa vocation universelle et humaniste.
Je salue la France qui, comme toujours dans les moments difficiles, sait se retrouver sur l'essentiel. Je salue les Françaises et les Français épris de solidarité et de liberté, soucieux de s'ouvrir à l'Europe et au monde, tournés vers l'avenir.
J'ai entendu et compris votre appel pour que la République vive, pour que la Nation se rassemble, pour que la politique change. Tout dans l'action qui sera conduite, devra répondre à cet appel et s'inspirer d'une exigence de service et d'écoute pour chaque Française et chaque Français.
Ce soir, je veux vous dire aussi mon émotion et le sentiment que j'ai de la responsabilité qui m'incombe.
Votre choix d'aujourd'hui est un choix fondateur, un choix qui renouvelle notre pacte républicain. Ce choix m'oblige comme il oblige chaque responsable de notre pays. Chacun mesure bien, à l'aune de notre histoire, la force de ce moment exceptionnel.
Votre décision, vous l'avez prise en conscience, en dépassant les clivages traditionnels, et, pour certains d'entre vous, en allant au-delà même de vos préférences personnelles ou politiques.
La confiance que vous venez de me témoigner, je veux y répondre en m'engageant dans l'action avec détermination.
Président de tous les Français, je veux y répondre dans un esprit de rassemblement. Je veux mettre la République au service de tous. Je veux que les valeurs de liberté, d'égalité et de fraternité reprennent toute leur place dans la vie de chacune et de chacun d'entre nous.
La liberté, c'est la sécurité, la lutte contre la violence, le refus de l'impunité. Faire reculer l'insécurité est la première priorité de l'Etat pour les temps à venir.
La liberté, c'est aussi la reconnaissance du travail et du mérite, la réduction des charges et des impôts.
L'égalité, c'est le refus de toute discrimination, ce sont les mêmes droits et les mêmes devoirs pour tous.
La fraternité, c'est sauvegarder les retraites. C'est aider les familles à jouer pleinement leur rôle. C'est faire en sorte que personne n'éprouve plus le sentiment d'être laissé pour compte.
La France, forte de sa cohésion sociale et de son dynamisme économique, portera en Europe et dans le monde l'ambition de la paix, des libertés et de la solidarité.
Dans les prochains jours, je mettrai en place un gouvernement de mission, un gouvernement qui aura pour seule tâche de répondre à vos préoccupations et d'apporter des solutions à des problèmes trop longtemps négligés. Son premier devoir sera de rétablir l'autorité de l'Etat pour répondre à l'exigence de sécurité, et de mettre la France sur un nouveau chemin de croissance et d'emploi.
C'est par une action forte et déterminée, c'est par la solidarité de la Nation, c'est par l'efficacité des résultats obtenus, que nous pourrons lutter contre l'intolérance, faire reculer l'extrémisme, garantir la vitalité de notre démocratie. Cette exigence s'impose à chacun d'entre nous. Elle impliquera, au cours des prochaines années, vigilance et mobilisation de la part de tous.
Mes chers compatriotes,
Le mandat que vous m'avez confié, je l'exercerai dans un esprit d'ouverture et de concorde, avec pour exigence l'unité de la République, la cohésion de la Nation et le respect de l'autorité de l'Etat.
Les jours que nous venons de vivre ont ranimé la vigueur nationale, la vigueur de l'idéal démocratique français. Ils ont exprimé une autre idée de la politique, une autre idée de la citoyenneté.
Chacune et chacun d'entre vous, conscient de ses responsabilités, par un choix de liberté, a contribué, ce soir, à forger le destin de la France.
Il y a là un espoir qui ne demande qu'à grandir, un espoir que je veux servir.
Vive la République !
Vive la France !
"""

# Appliquer les fonctions
text_no_punctuation = remove_punctuation(full_text)
text_lowercase = convert_to_lowercase(text_no_punctuation)
sentences = split_into_sentences(full_text)
tokens = tokenize(text_lowercase)
unique_tokens = remove_duplicates(tokens)

# Compter les phrases, les tokens et les tokens uniques
num_sentences = count_sentences(sentences)
num_tokens = count_tokens(tokens)
num_unique_tokens = count_unique_tokens(unique_tokens)

# Afficher les résultats
print(f"Nombre de phrases : {num_sentences}")
print(f"Nombre de tokens : {num_tokens}")
print(f"Nombre de tokens uniques : {num_unique_tokens}")
print(f"Tokens uniques : {unique_tokens}")

# Afficher le texte nettoyé avec les tokens uniques
cleaned_text = ' '.join(unique_tokens)
print(f"Texte nettoyé avec tokens uniques : {cleaned_text}")


Nombre de phrases : 37
Nombre de tokens : 673
Nombre de tokens uniques : 293
Tokens uniques : ['la', 'confiance', 'que', 'vous', 'venez', 'de', 'me', 'témoigner', 'je', 'veux', 'y', 'répondre', 'en', 'mengageant', 'dans', 'laction', 'avec', 'détermination', 'mes', 'chers', 'compatriotes', 'métropole', 'doutremer', 'et', 'létranger', 'nous', 'venons', 'vivre', 'un', 'temps', 'grave', 'inquiétude', 'pour', 'nation', 'mais', 'ce', 'soir', 'grand', 'élan', 'france', 'a', 'réaffirmé', 'son', 'attachement', 'aux', 'valeurs', 'république', 'salue', 'fidèle', 'à', 'ellemême', 'ses', 'grands', 'idéaux', 'sa', 'vocation', 'universelle', 'humaniste', 'qui', 'comme', 'toujours', 'les', 'moments', 'difficiles', 'sait', 'se', 'retrouver', 'sur', 'lessentiel', 'françaises', 'français', 'épris', 'solidarité', 'liberté', 'soucieux', 'souvrir', 'leurope', 'au', 'monde', 'tournés', 'vers', 'lavenir', 'jai', 'entendu', 'compris', 'votre', 'appel', 'vive', 'rassemble', 'politique', 'change', 'tout', 'sera'

In [30]:
import numpy as np
import pandas as pd

def create_bow_matrix(sentences, unique_tokens):
    """Create a binary Bag of Words matrix."""
    bow_matrix = []
    
    for sentence in sentences:
        # Tokeniser chaque phrase
        tokens = tokenize(convert_to_lowercase(remove_punctuation(sentence)))
        # Créer une ligne pour la matrice
        row = [1 if token in tokens else 0 for token in unique_tokens]
        bow_matrix.append(row)
        
    return np.array(bow_matrix)

# Créer la matrice BOW
bow_matrix = create_bow_matrix(sentences, unique_tokens)

# Créer un DataFrame pour une meilleure visualisation
bow_df = pd.DataFrame(bow_matrix, columns=unique_tokens)

# Afficher la matrice BOW avec étiquettes
print("Matrice Binaire (Bag of Words) :")
print(bow_df)


Matrice Binaire (Bag of Words) :
    la  confiance  que  vous  venez  de  me  témoigner  je  veux  ...  \
0    1          1    1     1      1   1   1          1   1     1  ...   
1    1          0    0     0      0   1   0          0   0     0  ...   
2    1          0    0     0      0   1   0          0   0     0  ...   
3    1          0    0     0      0   0   0          0   1     0  ...   
4    1          0    0     0      0   0   0          0   1     0  ...   
5    0          0    0     0      0   1   0          0   1     0  ...   
6    1          0    1     0      0   0   0          0   0     0  ...   
7    0          0    0     0      0   1   0          0   0     0  ...   
8    1          0    1     1      0   1   0          0   1     1  ...   
9    0          0    0     0      0   0   0          0   0     0  ...   
10   0          0    0     0      0   1   0          0   0     0  ...   
11   1          0    0     0      0   1   0          0   0     0  ...   
12   0          0 

In [31]:
import numpy as np
import pandas as pd

def create_occurrence_matrix(sentences, unique_tokens):
    """Create a Bag of Words occurrence matrix."""
    occurrence_matrix = []
    
    for sentence in sentences:
        # Tokeniser chaque phrase
        tokens = tokenize(convert_to_lowercase(remove_punctuation(sentence)))
        # Compter les occurrences
        row = [tokens.count(token) for token in unique_tokens]
        occurrence_matrix.append(row)
        
    return np.array(occurrence_matrix)

# Créer la matrice d'occurrences
occurrence_matrix = create_occurrence_matrix(sentences, unique_tokens)

# Créer un DataFrame pour une meilleure visualisation
occurrence_df = pd.DataFrame(occurrence_matrix, columns=unique_tokens)

# Afficher la matrice d'occurrences
print("Matrice d'Occurrences (Bag of Words) :")
print(occurrence_df)


Matrice d'Occurrences (Bag of Words) :
    la  confiance  que  vous  venez  de  me  témoigner  je  veux  ...  \
0    1          1    1     1      1   1   1          1   1     1  ...   
1    1          0    0     0      0   4   0          0   0     0  ...   
2    2          0    0     0      0   1   0          0   0     0  ...   
3    1          0    0     0      0   0   0          0   1     0  ...   
4    1          0    0     0      0   0   0          0   1     0  ...   
5    0          0    0     0      0   3   0          0   1     0  ...   
6    3          0    3     0      0   0   0          0   0     0  ...   
7    0          0    0     0      0   1   0          0   0     0  ...   
8    1          0    1     1      0   1   0          0   1     1  ...   
9    0          0    0     0      0   0   0          0   0     0  ...   
10   0          0    0     0      0   1   0          0   0     0  ...   
11   1          0    0     0      0   2   0          0   0     0  ...   
12   0      

In [33]:
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform



# Calculer la distance euclidienne pour la matrice binaire
binary_distance_matrix = squareform(pdist(bow_matrix, metric='euclidean'))

# Créer un DataFrame pour la matrice de distance binaire
binary_distance_df = pd.DataFrame(binary_distance_matrix, 
                                   columns=[f'Document {i+1}' for i in range(len(bow_matrix))],
                                   index=[f'Document {i+1}' for i in range(len(bow_matrix))])

# Afficher la matrice de distance binaire
print("Matrice de Distance Euclidienne (Binaire) :")
print(binary_distance_df)

# Calculer la distance euclidienne pour la matrice d'occurrences
occurrence_distance_matrix = squareform(pdist(occurrence_matrix, metric='euclidean'))

# Créer un DataFrame pour la matrice de distance d'occurrences
occurrence_distance_df = pd.DataFrame(occurrence_distance_matrix, 
                                       columns=[f'Document {i+1}' for i in range(len(occurrence_matrix))],
                                       index=[f'Document {i+1}' for i in range(len(occurrence_matrix))])

# Afficher la matrice de distance d'occurrences
print("\nMatrice de Distance Euclidienne (Occurrences) :")
print(occurrence_distance_df)


Matrice de Distance Euclidienne (Binaire) :
             Document 1  Document 2  Document 3  Document 4  Document 5  \
Document 1     0.000000    5.656854    5.385165    5.385165    5.291503   
Document 2     5.656854    0.000000    5.385165    5.385165    5.656854   
Document 3     5.385165    5.385165    0.000000    5.291503    5.196152   
Document 4     5.385165    5.385165    5.291503    0.000000    4.795832   
Document 5     5.291503    5.656854    5.196152    4.795832    0.000000   
Document 6     5.744563    5.744563    5.830952    5.099020    5.385165   
Document 7     5.477226    5.099020    5.385165    5.196152    5.291503   
Document 8     5.656854    5.830952    5.916080    5.744563    5.830952   
Document 9     5.000000    5.567764    5.291503    5.291503    5.385165   
Document 10    5.385165    5.196152    5.099020    5.099020    5.000000   
Document 11    5.196152    5.196152    4.898979    5.099020    5.000000   
Document 12    5.196152    5.196152    4.898979    4.898

In [36]:
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform

# Supposons que 'bow_matrix' (matrice binaire) et 'occurrence_matrix' (matrice d'occurrences) sont déjà créées

# Calculer la distance de Manhattan pour la matrice binaire
binary_distance_matrix = squareform(pdist(bow_matrix, metric='cityblock'))

# Créer un DataFrame pour la matrice de distance binaire
binary_distance_df = pd.DataFrame(binary_distance_matrix, 
                                   columns=[f'Document {i+1}' for i in range(len(bow_matrix))],
                                   index=[f'Document {i+1}' for i in range(len(bow_matrix))])

# Afficher la matrice de distance binaire
print("Matrice de Distance de Manhattan (Binaire) :")
print(binary_distance_df)

# Calculer la distance de Manhattan pour la matrice d'occurrences
occurrence_distance_matrix = squareform(pdist(occurrence_matrix, metric='cityblock'))

# Créer un DataFrame pour la matrice de distance d'occurrences
occurrence_distance_df = pd.DataFrame(occurrence_distance_matrix, 
                                       columns=[f'Document {i+1}' for i in range(len(occurrence_matrix))],
                                       index=[f'Document {i+1}' for i in range(len(occurrence_matrix))])

# Afficher la matrice de distance d'occurrences
print("\nMatrice de Distance de Manhattan (Occurrences) :")
print(occurrence_distance_df)


Matrice de Distance de Manhattan (Binaire) :
             Document 1  Document 2  Document 3  Document 4  Document 5  \
Document 1          0.0        32.0        29.0        29.0        28.0   
Document 2         32.0         0.0        29.0        29.0        32.0   
Document 3         29.0        29.0         0.0        28.0        27.0   
Document 4         29.0        29.0        28.0         0.0        23.0   
Document 5         28.0        32.0        27.0        23.0         0.0   
Document 6         33.0        33.0        34.0        26.0        29.0   
Document 7         30.0        26.0        29.0        27.0        28.0   
Document 8         32.0        34.0        35.0        33.0        34.0   
Document 9         25.0        31.0        28.0        28.0        29.0   
Document 10        29.0        27.0        26.0        26.0        25.0   
Document 11        27.0        27.0        24.0        26.0        25.0   
Document 12        27.0        27.0        24.0        

In [22]:
import re
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform

# Supposons que 'full_text' est votre texte d'entrée.

# 1. Fonction pour nettoyer et tokeniser le texte
def preprocess_text(text):
    text_no_punctuation = re.sub(r'[^\w\s]', '', text)
    text_lowercase = text_no_punctuation.lower()
    tokens = text_lowercase.split()
    unique_tokens = sorted(set(tokens))  # Obtenir les mots uniques en ordre alphabétique
    return unique_tokens, tokens

# 2. Créer la matrice binaire
def create_binary_matrix(unique_tokens, tokens):
    binary_matrix = []
    sentences = split_into_sentences(full_text)  # Réutiliser la fonction de votre code précédent

    for sentence in sentences:
        row = [1 if token in sentence.lower() else 0 for token in unique_tokens]
        binary_matrix.append(row)

    return np.array(binary_matrix), sentences

# 3. Traitement du texte et création de la matrice binaire
unique_tokens, tokens = preprocess_text(full_text)
bow_matrix, sentences = create_binary_matrix(unique_tokens, tokens)

# 4. Calculer la distance de Manhattan pour la matrice binaire
binary_distance_matrix = squareform(pdist(bow_matrix, metric='cityblock'))

# 5. Créer un DataFrame pour la matrice de distance binaire
binary_distance_df = pd.DataFrame(binary_distance_matrix, 
                                   columns=[f'Sentence {i+1}' for i in range(len(bow_matrix))],
                                   index=[f'Sentence {i+1}' for i in range(len(bow_matrix))])

# Afficher les résultats
print("Matrice Binaire (Bag of Words) :")
print(bow_matrix)

print("\nMatrice de Distance de Manhattan (Binaire) :")
print(binary_distance_df)

# Afficher la liste des tokens uniques
print("\nMots uniques en ordre alphabétique :")
print(unique_tokens)


Matrice Binaire (Bag of Words) :
[[1 1 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 1 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]]

Matrice de Distance de Manhattan (Binaire) :
             Sentence 1  Sentence 2  Sentence 3  Sentence 4  Sentence 5  \
Sentence 1          0.0        31.0        29.0        38.0        32.0   
Sentence 2         31.0         0.0        32.0        37.0        33.0   
Sentence 3         29.0        32.0         0.0        29.0        33.0   
Sentence 4         38.0        37.0        29.0         0.0        30.0   
Sentence 5         32.0        33.0        33.0        30.0         0.0   
Sentence 6         39.0        38.0        40.0        31.0        33.0   
Sentence 7         30.0        27.0        31.0        36.0        32.0   
Sentence 8         31.0        36.0        38.0        43.0        39.0   
Sentence 9         25.0        30.0        28.0        31.0        25.0   
Sentence 10        32.0        27.0        29.0    

In [23]:
import re
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform

# Supposons que 'full_text' est votre texte d'entrée.

# 1. Fonction pour nettoyer et tokeniser le texte
def preprocess_text(text):
    text_no_punctuation = re.sub(r'[^\w\s]', '', text)
    text_lowercase = text_no_punctuation.lower()
    tokens = text_lowercase.split()
    unique_tokens = sorted(set(tokens))  # Obtenir les mots uniques en ordre alphabétique
    return unique_tokens, tokens

# 2. Créer la matrice d'occurrences
def create_occurrence_matrix(unique_tokens, tokens):
    occurrence_matrix = []
    sentences = split_into_sentences(full_text)  # Réutiliser la fonction de votre code précédent

    for sentence in sentences:
        row = [sentence.lower().count(token) for token in unique_tokens]
        occurrence_matrix.append(row)

    return np.array(occurrence_matrix), sentences

# 3. Traitement du texte et création de la matrice d'occurrences
unique_tokens, tokens = preprocess_text(full_text)
occurrence_matrix, sentences = create_occurrence_matrix(unique_tokens, tokens)

# 4. Calculer la distance de Manhattan pour la matrice d'occurrences
occurrence_distance_matrix = squareform(pdist(occurrence_matrix, metric='cityblock'))

# 5. Créer un DataFrame pour la matrice de distance d'occurrences
occurrence_distance_df = pd.DataFrame(occurrence_distance_matrix, 
                                       columns=[f'Sentence {i+1}' for i in range(len(occurrence_matrix))],
                                       index=[f'Sentence {i+1}' for i in range(len(occurrence_matrix))])

# Afficher les résultats
print("Matrice d'Occurrences (Bag of Words) :")
print(occurrence_matrix)

print("\nMatrice de Distance de Manhattan (Occurrences) :")
print(occurrence_distance_df)

# Afficher la liste des tokens uniques
print("\nMots uniques en ordre alphabétique :")
print(unique_tokens)


Matrice d'Occurrences (Bag of Words) :
[[ 8  1  0 ...  0  0  0]
 [ 5  0  0 ...  0  0  0]
 [13  0  0 ...  1  0  0]
 ...
 [ 7  0  0 ...  0  0  0]
 [ 3  0  0 ...  0  0  0]
 [ 3  0  0 ...  0  0  0]]

Matrice de Distance de Manhattan (Occurrences) :
             Sentence 1  Sentence 2  Sentence 3  Sentence 4  Sentence 5  \
Sentence 1          0.0        44.0        40.0        52.0        44.0   
Sentence 2         44.0         0.0        50.0        58.0        42.0   
Sentence 3         40.0        50.0         0.0        48.0        52.0   
Sentence 4         52.0        58.0        48.0         0.0        46.0   
Sentence 5         44.0        42.0        52.0        46.0         0.0   
Sentence 6         52.0        48.0        58.0        50.0        46.0   
Sentence 7         43.0        45.0        47.0        57.0        47.0   
Sentence 8         50.0        56.0        54.0        68.0        60.0   
Sentence 9         31.0        39.0        41.0        47.0        33.0   
Sente

In [21]:
import re
import numpy as np
import pandas as pd
from scipy.spatial.distance import pdist, squareform

# Texte d'entrée


# 1. Découper le texte en phrases
def split_into_sentences(text):
    """Split the text into sentences using punctuation."""
    sentences = re.split(r'\.', text)
    return [sentence.strip() for sentence in sentences if sentence.strip()]

# 2. Prétraitement du texte
def preprocess_text(sentences):
    unique_tokens = set()  # Utiliser un ensemble pour les mots uniques
    for sentence in sentences:
        # Nettoyer et tokeniser
        tokens = re.findall(r'\b\w+\b', sentence.lower())
        unique_tokens.update(tokens)  # Ajouter les mots uniques
    return sorted(unique_tokens)  # Retourner une liste triée

# 3. Créer la matrice binaire et la matrice d'occurrences
def create_matrices(sentences, unique_tokens):
    binary_matrix = []
    occurrence_matrix = []
    
    for sentence in sentences:
        # Tokeniser la phrase
        tokens = re.findall(r'\b\w+\b', sentence.lower())
        
        # Créer une ligne pour la matrice binaire
        binary_row = [1 if token in tokens else 0 for token in unique_tokens]
        binary_matrix.append(binary_row)
        
        # Créer une ligne pour la matrice d'occurrences
        occurrence_row = [tokens.count(token) for token in unique_tokens]
        occurrence_matrix.append(occurrence_row)

    return np.array(binary_matrix), np.array(occurrence_matrix)

# 4. Calculer la distance de Manhattan
def calculate_manhattan_distance(matrix):
    return squareform(pdist(matrix, metric='cityblock'))

# 5. Calculer la distance euclidienne
def calculate_euclidean_distance(matrix):
    return squareform(pdist(matrix, metric='euclidean'))

# Traitement des phrases
sentences = split_into_sentences(full_text)
unique_tokens = preprocess_text(sentences)

# Création des matrices
binary_matrix, occurrence_matrix = create_matrices(sentences, unique_tokens)

# Calculer les distances de Manhattan
binary_distance_manhattan = calculate_manhattan_distance(binary_matrix)
occurrence_distance_manhattan = calculate_manhattan_distance(occurrence_matrix)

# Calculer les distances euclidiennes
binary_distance_euclidean = calculate_euclidean_distance(binary_matrix)
occurrence_distance_euclidean = calculate_euclidean_distance(occurrence_matrix)

# Créer des DataFrames pour afficher les distances
binary_distance_manhattan_df = pd.DataFrame(binary_distance_manhattan, 
                                             columns=[f'Doc {i+1}' for i in range(len(sentences))],
                                             index=[f'Doc {i+1}' for i in range(len(sentences))])

occurrence_distance_manhattan_df = pd.DataFrame(occurrence_distance_manhattan, 
                                                columns=[f'Doc {i+1}' for i in range(len(sentences))],
                                                index=[f'Doc {i+1}' for i in range(len(sentences))])

binary_distance_euclidean_df = pd.DataFrame(binary_distance_euclidean, 
                                             columns=[f'Doc {i+1}' for i in range(len(sentences))],
                                             index=[f'Doc {i+1}' for i in range(len(sentences))])

occurrence_distance_euclidean_df = pd.DataFrame(occurrence_distance_euclidean, 
                                                columns=[f'Doc {i+1}' for i in range(len(sentences))],
                                                index=[f'Doc {i+1}' for i in range(len(sentences))])

# Afficher les résultats
print("Matrice Binaire (Bag of Words) :")
print(binary_matrix)

print("\nMatrice d'Occurrences (Bag of Words) :")
print(occurrence_matrix)

print("\nMatrice de Distance de Manhattan (Binaire) :")
print(binary_distance_manhattan_df)

print("\nMatrice de Distance de Manhattan (Occurrences) :")
print(occurrence_distance_manhattan_df)

print("\nMatrice de Distance Euclidienne (Binaire) :")
print(binary_distance_euclidean_df)

print("\nMatrice de Distance Euclidienne (Occurrences) :")
print(occurrence_distance_euclidean_df)

print("\nMots uniques en ordre alphabétique :")
print(unique_tokens)


Matrice Binaire (Bag of Words) :
[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Matrice d'Occurrences (Bag of Words) :
[[0 1 0 ... 0 0 0]
 [0 0 0 ... 0 1 0]
 [1 0 0 ... 0 0 0]
 ...
 [1 0 0 ... 0 0 0]
 [1 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Matrice de Distance de Manhattan (Binaire) :
        Doc 1  Doc 2  Doc 3  Doc 4  Doc 5  Doc 6  Doc 7  Doc 8  Doc 9  Doc 10  \
Doc 1     0.0   35.0   31.0   32.0   29.0   35.0   33.0   35.0   27.0    33.0   
Doc 2    35.0    0.0   32.0   33.0   34.0   36.0   30.0   36.0   36.0    30.0   
Doc 3    31.0   32.0    0.0   29.0   28.0   36.0   30.0   38.0   30.0    28.0   
Doc 4    32.0   33.0   29.0    0.0   25.0   29.0   29.0   37.0   31.0    29.0   
Doc 5    29.0   34.0   28.0   25.0    0.0   30.0   30.0   36.0   32.0    28.0   
Doc 6    35.0   36.0   36.0   29.0   30.0    0.0   36.0   34.0   36.0    34.0   
Doc 7    33.0   30.0   30.0   29.0   30.0   36.0    0.0   36.0   28.0    2