In [1]:
%run TP1.ipynb


---------- Corpus Obama ------------

Le nombre de phrases est : 84
Le nombre de tokens est : 658
---------- Corpus Chirac ------------

Le nombre de phrases est : 37
Le nombre de tokens est : 293


In [2]:
def bow_bin(document, vocabulaire):
    bow_bin = [1 if token in document.split() else 0 for token in vocabulaire]
    return bow_bin

In [3]:
def bow_occ(document, vocabulaire):
    bow_occ = [document.split().count(token) for token in vocabulaire]
    return bow_occ

In [4]:
bow_bin(sentences[0], tokens)

[0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 1,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 0,
 1,
 0,
 0,
 0,
 0,
 0,
 0,


In [5]:
def distance_euclidean(vect1, vect2):
    sum = 0
    for i in range(len(vect1)):
        sum += math.pow(vect1[i] - vect2[i], 2)
    
    return math.sqrt(sum)

In [6]:
def distance_manhattan(vect1, vect2):
    sum = 0
    for i in range(len(vect1)):
        sum += abs(vect1[i] - vect2[i])
    
    return sum

In [7]:
import numpy as np # pour l'affichage seulement
import math

#sentences = [
#    "the cat sat on the mat",
#    "the dog sat on the log",
#    "the cat and dog are friends"
#]
#tokens = list(set(" ".join(sentences).split()))

# création des matrices BoW
bow_bin_matrix = [bow_bin(sentence, tokens) for sentence in sentences]
bow_occ_matrix = [bow_occ(sentence, tokens) for sentence in sentences]

# affichage
print("Matrice BoW-bin :")
print(np.array(bow_bin_matrix))


print("\nMatrice BoW-occ:")
print(np.array(bow_occ_matrix))


# initialisation des matrices de distances
euclidean_occ_matrix = [[0] * len(sentences) for _ in range(len(sentences))]
manhattan_occ_matrix = [[0] * len(sentences) for _ in range(len(sentences))]
euclidean_bin_matrix = [[0] * len(sentences) for _ in range(len(sentences))]
manhattan_bin_matrix = [[0] * len(sentences) for _ in range(len(sentences))]

# calcul des distances et remplissage des matrices 
for i in range(len(sentences)):
    for j in range(len(sentences)):
        if i != j:
            euclidean_occ_matrix[i][j] = distance_euclidean(bow_occ_matrix[i], bow_occ_matrix[j])
            manhattan_occ_matrix[i][j] = distance_manhattan(bow_occ_matrix[i], bow_occ_matrix[j])
            euclidean_bin_matrix[i][j] = distance_euclidean(bow_bin_matrix[i], bow_bin_matrix[j])
            manhattan_bin_matrix[i][j] = distance_manhattan(bow_bin_matrix[i], bow_bin_matrix[j])

# affichage
print("\nMatrice de similarité avec BoW-bin et la distance euclidéene:")
print(np.array(euclidean_bin_matrix))

print("\nMatrice de similarité avec BoW-bin et la distance manhattan:")
print(np.array(manhattan_bin_matrix))


print("\nMatrice de similarité avec BoW-occ et la distance euclidéene:")
print(np.array(euclidean_occ_matrix))


print("\nMatrice de similarité avec BoW-occ et la distance manhattan:")
print(np.array(manhattan_occ_matrix))


Matrice BoW-bin :
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Matrice BoW-occ:
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]

Matrice de similarité avec BoW-bin et la distance euclidéene:
[[0.         5.09901951 5.         ... 4.47213595 4.         4.        ]
 [5.09901951 0.         5.         ... 5.09901951 4.         4.        ]
 [5.         5.         0.         ... 5.         3.87298335 3.87298335]
 ...
 [4.47213595 5.09901951 5.         ... 0.         4.         4.        ]
 [4.         4.         3.87298335 ... 4.         0.         1.41421356]
 [4.         4.         3.87298335 ... 4.         1.41421356 0.        ]]

Matrice de similarité avec BoW-bin et la distance manhattan:
[[ 0 26 25 ... 20 16 16]
 [26  0 25 ... 26 16 16]
 [25 25  0 ... 25 15 15]
 ...
 [20 26 25 ...  0 16 16]
 [16 16 15 ... 16  0  2]
 [16 16 15 ... 16  2  0]]

In [8]:
def K_plus_proches_documents(doc_query, k, sentences, similarity_matrix, tokens):
    # si le document est parmis la liste
    if doc_query in sentences:
        doc_idx = sentences.index(doc_query) # recuperer l'index
        doc_vector = similarity_matrix[doc_idx]
        k_documents = sorted(range(len(doc_vector)), key=lambda i: doc_vector[i])[:k]
    # nouveau document
    else:
        doc_query_bow_occ = bow_occ(doc_query, tokens) # représantation BoW
        doc_query_sim = []
        for i in range(len(sentences)): # calcul des distances
            doc_query_sim.append(distance_euclidean(bow_occ_matrix[i], doc_query_bow_occ))
        print(doc_query_sim)
        # recuperation des indexes des plus proches
        k_documents = sorted(range(len(doc_query_sim)), key=lambda i: doc_query_sim[i])[:k]
        
    return [sentences[i] for i in k_documents]

In [9]:
doc_query = "france"
k = 5

K_plus_proches_documents(doc_query, k, sentences, euclidean_occ_matrix, tokens)

[4.0, 5.5677643628300215, 4.242640687119285, 5.385164807134504, 3.4641016151377544, 5.830951894845301, 6.164414002968976, 5.385164807134504, 4.123105625617661, 4.58257569495584, 3.3166247903554, 3.7416573867739413, 5.0990195135927845, 4.0, 4.0, 3.1622776601683795, 6.082762530298219, 4.69041575982343, 3.605551275463989, 5.291502622129181, 4.47213595499958, 2.23606797749979, 3.0, 3.4641016151377544, 7.0710678118654755, 6.48074069840786, 6.6332495807108, 6.4031242374328485, 2.449489742783178, 4.0, 7.615773105863909, 4.795831523312719, 5.0, 4.898979485566356, 4.47213595499958, 2.0, 1.4142135623730951]


['vive la france',
 'vive la république',
 "la fraternité, c'est sauvegarder les retraites",
 "cette exigence s'impose à chacun d'entre nous",
 "c'est aider les familles à jouer pleinement leur rôle"]